name: Deploy DbUp

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: us-east-1
  S3_BUCKET: dbup-artifacts-bucket
  CODEBUILD_PROJECT: dbup-project

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore and Build DbUp project
      run: |
        dotnet restore ./DbUpSqlServerPOC
        dotnet publish ./DbUpSqlServerPOC -c Release -o ./publish

    - name: Zip publish folder
      run: |
        cd publish
        zip -r ../publish.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload publish.zip to S3
      run: |
        aws s3 cp publish.zip s3://${{ env.S3_BUCKET }}/publish.zip

    - name: Trigger CodeBuild
      run: |
        aws codebuild start-build --project-name ${{ env.CODEBUILD_PROJECT }}
