name: Deploy DbUp

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./DbUpSqlServerPOC.csproj

      - name: Publish DbUp project
        run: dotnet publish ./DbUpSqlServerPOC.csproj -c Release -o ./publish

      - name: Upload published files to S3
        run: aws s3 cp ./publish s3://$S3_BUCKET/ --recursive
        env:
          AWS_REGION: us-east-1
          S3_BUCKET: dbup-artifacts-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Trigger CodeBuild deployment
        run: aws codebuild start-build --project-name $CODEBUILD_PROJECT
        env:
          AWS_REGION: us-east-1
          CODEBUILD_PROJECT: dbup-project
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
