name: Deploy DbUp

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./DbUpSqlServerPOC.csproj

      - name: Publish DbUp project
        run: dotnet publish ./DbUpSqlServerPOC.csproj -c Release -o ./publish

      - name: Set environment-specific variables
        id: set-vars
        run: |
          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            echo "S3_BUCKET=${{ vars.S3_BUCKET_DEV }}" >> $GITHUB_ENV
            echo "CODEBUILD_PROJECT=${{ vars.CODEBUILD_PROJECT_DEV }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "staging" ]; then
            echo "S3_BUCKET=${{ vars.S3_BUCKET_STAGING }}" >> $GITHUB_ENV
            echo "CODEBUILD_PROJECT=${{ vars.CODEBUILD_PROJECT_STAGING }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "S3_BUCKET=${{ vars.S3_BUCKET_PROD }}" >> $GITHUB_ENV
            echo "CODEBUILD_PROJECT=${{ vars.CODEBUILD_PROJECT_PROD }}" >> $GITHUB_ENV
          fi

      - name: Upload published files to S3
        run: aws s3 cp ./publish s3://$S3_BUCKET/ --recursive
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Trigger CodeBuild deployment
        run: aws codebuild start-build --project-name $CODEBUILD_PROJECT
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
