name: Deploy DbUp

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./DbUpSqlServerPOC.csproj

      - name: Publish DbUp project
        run: dotnet publish ./DbUpSqlServerPOC.csproj -c Release -o ./publish

      - name: Upload published files to environment-specific S3 bucket
        run: aws s3 cp ./publish s3://$S3_BUCKET/ --recursive
        env:
          AWS_REGION: us-east-1
          S3_BUCKET: ${{ vars[format('S3_BUCKET_{0}', github.event.inputs.environment | upper)] }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Trigger environment-specific CodeBuild project
        run: aws codebuild start-build --project-name $CODEBUILD_PROJECT
        env:
          AWS_REGION: us-east-1
          CODEBUILD_PROJECT: ${{ vars[format('CODEBUILD_PROJECT_{0}', github.event.inputs.environment | upper)] }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
